services:
  serve:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: serve --dev-addr 0.0.0.0:8000

  build:
    image: squidfunk/mkdocs-material
    container_name: mkdocs-build
    volumes:
      - .:/docs
    command: build